<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251120222801 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE email_notification (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(128) NOT NULL, text VARCHAR(512) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE feed (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tweets JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reader_id BIGINT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_234044AB1717D737 ON feed (reader_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE sms_notification (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, phone VARCHAR(11) NOT NULL, text VARCHAR(60) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE feed ADD CONSTRAINT FK_234044AB1717D737 FOREIGN KEY (reader_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE feed DROP CONSTRAINT FK_234044AB1717D737
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE email_notification
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE feed
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE sms_notification
        SQL);
    }
}
